### ISSUE TITLE
🐞 bug: application.html: line 17: _footer.html: line 3: year: unknown identifier

### ISSUE THREAD

**Issue by johnrlive** [markbates/buffalo-bootstrap#1]
Hi @markbates 

I installed the buffalo-bootstrap plugin and I got this error by default. I had to remove <%= year %> and was able to fix it. 

Is this a bug or is plush not installed by default?

![_footer_html_ _coke](https://user-images.githubusercontent.com/535279/35639861-861841ba-0689-11e8-8290-0c55d34c3dea.png)

**Comment by markbates** [comment]
It's not really a bug. :)

I didn't really think anyone would ever use this plugin except for me, so I didn't really consider it.

The `year` is either meant to be removed, or set in the context of a Buffalo app like this:

```go
app.Use(func(next buffalo.Handler) buffalo.Handler {
	return func(c buffalo.Context) error {
		c.Set("year", time.Now().Year())
		return next(c)
	}
})
```
